 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild PosLib/PosLib.csproj /t:restore
       - run: msbuild PosLib/PosLib.csproj /p:Configuration=Release
       - run: 
          name: Push to NuGet
          command: |
            PosLib/NuGet-Push.ps1
            
